### ISSUE TITLE
train on DOTAdataset

### ISSUE THREAD

**Issue by Marcus208** [ming71/DAL#14]
Hi, thanks for your great job! But when i run the code on dota_dataset, there has something wrong with the data processing:
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train_model(arg, hyps)
  File "train.py", line 147, in train_model
    for i, (ni, batch) in enumerate(pbar):
  File "/home/cyli/dat01/anaconda3/envs/dal/lib/python3.7/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/cyli/dat01/anaconda3/envs/dal/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/cyli/dat01/anaconda3/envs/dal/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
IndexError: Traceback (most recent call last):
  File "/home/cyli/dat01/anaconda3/envs/dal/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cyli/dat01/anaconda3/envs/dal/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/scratch/cyli/lcy/DAL/datasets/dota_dataset.py", line 40, in __getitem__
    bboxes = roidb['boxes'][gt_inds, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by Marcus208** [comment]
Finally, this issue is caused by the annotation files without any annotation.

**Comment by wfnian** [comment]
how did you solve this issue?
