### ISSUE TITLE
训练DOTA数据集有空标签就会报这个错误

### ISSUE THREAD

**Issue by icey-zhang** [ming71/DAL#51]
Namespace(augment=False, backbone='res50', dataset='DOTA', freeze_bn=False, hyp='hyp.py', load=False, multi_scale=False, resume=False, target_size=[800], train_path='/home/pan1/dataset/DOTA-v1.0_split_800/trainval.txt', training_size=800, weight='')
{'lr0': 0.0001, 'warmup_lr': 1e-05, 'warm_epoch': 5.0, 'num_classes': 15.0, 'epochs': 100.0, 'batch_size': 16.0, 'save_interval': 5.0, 'test_interval': 5.0}
Model Summary: 195 layers, 3.63713e+07 parameters, 3.63713e+07 gradients

     Epoch   gpu_mem       cls       reg     total   targets  img_size
  0%|                                                                                           | 0/2364 [02:55<?, ?it/s]
Traceback (most recent call last):
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zjq/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/zjq/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/zjq/.vscode-server/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pan1/zjq/DAL/train.py", line 281, in <module>
    train_model(arg, hyps)
  File "/home/pan1/zjq/DAL/train.py", line 146, in train_model
    for i, (ni, batch) in enumerate(pbar):
  File "/home/zjq/.local/lib/python3.7/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zhangemo/anaconda3/envs/zjq/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/pan1/zjq/DAL/datasets/dota_dataset.py", line 40, in __getitem__
    bboxes = roidb['boxes'][gt_inds, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by ming71** [comment]
Refer to #13.
